# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

default: &default
  adapter: mysql2
  username: root
  password: root
  port: 3306
  pool: 5
  timeout: 5000

development:
  <<: *default
  host: db
  database: hyrax

test:
  <<: *default
  host: db_test
  database: hyrax

production:
  <<: *default
  database: db/production.sqlite3
