development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://fcrepo:8984/fcrepo/rest
  base_path: /dev
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://fcrepo:8984/fcrepo/rest
  base_path: /test
production:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://192.168.99.100:8983/fedora/rest
  base_path: /prod
