# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 278266519e3a1acb6a915e709c54e1ddcf587c948215d27231693e0d35cee6cf79d81fadfd3d6e19f83711d132fc6d06707c2b3faf080db963e9dbf1a2372414

test:
  secret_key_base: 7975178ecd3886d51b60dde567467b436d7ca45db6ec41adde94787a7bb63f24a0c3be6a01de98b066a653a6c890fef214ac5495d6d660dfe4eca7cb09cda34e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
